version: '3.3'
services:
  app:
    image: "ghcr.io/tyler71/panda-api:latest"
    restart: unless-stopped
    build:
      context: .
      target: dev
    ports:
        - '8080:8000'
    volumes:
      - './app:/app'
    env_file:
      - '.env'
    networks:
      - internal
# db:
#   image: postgres:15-bullseye
#   environment:
#     - POSTGRES_USER=app
#     - POSTGRES_PASSWORD=${DB_PASS}
#     - POSTGRES_DB=app
#   volumes:
#     - "./data/db:/var/lib/postgresql/data"
#   ports:
#     - '50332:5432'
#   restart: unless-stopped
#   networks:
#     - internal

networks:
  internal:
