name: Build and deploy to flyio

on:
# create:
#   tags:
#     - "v*.*.*"
  push:
    branches:
      - master
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

#     - name: 👀 Read app name
#       uses: SebRollen/toml-action@v1.0.0
#       id: app_name
#       with:
#         file: "fly.toml"
#         field: "app"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#     - uses: superfly/flyctl-actions/setup-flyctl@master
#     - run: flyctl auth docker
#       env:
#         FLY_API_TOKEN: ${{ secrets.FLYIO_ACCESS_TOKEN }}

#     - name: Login to Fly Registry
#       uses: docker/login-action@v1
#       with:
#         registry: registry.fly.io
#         username: ${{ secrets.FLYIO_USERNAME }}
#         password: ${{ secrets.FLYIO_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context:    .
          target:     prod
          push:       true
          tags:       |
            ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest
            ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ github.run_number }}
            ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ github.run_number }}
#           registry.fly.io/${{ github.event.repository.name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to:   type=gha,mode=max

#     - uses: superfly/flyctl-actions/setup-flyctl@master
#     - run: flyctl deploy --local-only --image registry.fly.io/${{ github.event.repository.name }}:${{ github.sha }}
#       env:
#         FLY_API_TOKEN: ${{ secrets.FLYIO_ACCESS_TOKEN }}
